### ISSUE TITLE
Keep Fathom open source

### ISSUE THREAD

**Issue by skyfaller** [usefathom/fathom#268]
I see on https://usefathom.com/ that you say "our next version (2.0) will only be available to our paid customers." That is very disappointing to me, as I want to use and support Fathom, but if future improvements will not go to the open source project I don't know if I'm willing to invest anything into it.

Please reconsider! If I end up in a position where I can buy your hosted version I will happily do so if it's open source, but I will look into other options if it's not. Why remove one of your big advantages over e.g. Google Analytics? I don't trust code I can't see.

**Comment by pokrface** [comment]
Disappointing.

**Comment by JackEllis** [comment]
Our biggest advantage over google analytics is that we won’t / don’t collect personal data.

Have you contributed to the codebase before (I couldn’t find anything)? Or have you not contributed yet but want to?

**Comment by pjrvs** [comment]
We are keeping this version open-source, forever, and committing to maintain it. We also have a business to run, and while we love open-source, it isn't paying our bills (and Fathom takes a lot of work from 2 people to keep going) and we're not a charity.

If this repo was full of contributions and other folks pitching in, this would be a different story, but it's not—which is totally fine and accepted. But, since we want to keep going with Fathom, we have to separate V1 and V2 so we can make it sustainable. Otherwise we'd have to abandon it (which serves no one).

If you truly want your complaint heard, maybe contribute to what you're complaining about (financially, time, effort, etc).

**Comment by skyfaller** [comment]
Thank you for making your position clear. I only discovered Fathom a few weeks ago, so I have not made any contributions yet, but I was interested in using it for a potentially large deployment of non-profit websites, which could lead to code contributions or monetary contributions in the future. I like the privacy focus and that it's written in Go, I'm currently running the Caddy webserver and Hugo static site generators which are also written in Go.

It sounds like to me you would think differently about open sourcing future versions if there were more contributions from the community. What would that look like? Could we still work to make it happen? It seems premature to write off the community when there are probably many people like me who simply haven't heard of your product yet.

**Comment by JackEllis** [comment]
@skyfaller Hey Nelson - We can't afford to work off of "what if" hypotheticals, I'm afraid. We have committed to maintaining Fathom OS moving forward but open-sourcing our PRO version creates a whole new set of issues for us. For example, our PRO version has a sophisticated infrastructure set-up with specific redundancy, built to handle billions of requests, so it would add more complexity to the OS version and be a headache to make it compatible with all sorts of services other than the ones we choose to use for our hosting. Another big piece is that our PRO version is coded with Laravel / Lumen / EmberJS, and a lot of the community like OS Fathom because it's written in Go. We don't want to change that.

We really do appreciate your input but we've gone into the OS PRO option in great depth over the last 6 months and we're going to be proceeding as previously stated.

**Comment by m1guelpf** [comment]
Here's another suggestion to consider: How about adding your PRO customers to the v2 repo? That way others can contribute to the hosted version they're paying for but you still get paid. This model is used by Laravel Nova or Laravel Spark, for example.

**Comment by JackEllis** [comment]
@m1guelpf Not a bad idea, Miguel. We'll add it to our list of discussion points.

**Comment by arp242** [comment]
> If this repo was full of contributions and other folks pitching in, this would be a different story, but it's not. [..]  If you truly want your complaint heard, maybe contribute to what you're complaining about (financially, time, effort, etc). My wife always tells me that I'm not allowed to gripe unless I'm also taking action.

I don't mean this in an accusatory way, but [my trivial PR](https://github.com/usefathom/fathom/pull/250) is still ignored. I find it a bit strange to complain about the lack of contributions while ignoring people who try to contribute. This sort of thing needs participation from both sides.

In the meanwhile, I wrote my own replacement for Fathom as this project seemed dead, but I would have happily contributed to Fathom if I had gotten some feedback.

**Comment by JackEllis** [comment]
@arp242 You're right, there are PRs that should be merged. Honestly, it's a time thing. We are hoping to bring in some paid Go resource by the end of the year to handle this (using the pro service to fund it) or I need to learn Go (I've never written Go). It's not a case of ignoring, it's a case that we have to prioritize. Our objective, long term, is to make this codebase completely sustainable for many years to come. To do that, our pro service will fund its development.

Anyway, I appreciate the feedback and agree with you wholeheartedly. We're trying to get a lot of things done and we only have so much time outside of our regular occupations. And I want to apologize for making you feel like your PR doesn't matter, because it does, so thank you for submitting it.

**Comment by arp242** [comment]
Yeah, I understand that accepting PRs isn't "free", you still need to spend time communicating, reviewing, etc. I know I've forgotten about plenty of PRs people have submitted to my own projects!

I don't really care about my PR: it's trivial (just the output of one command) and updates some stuff so the code is easier to work with (there's been a lot of changes to Go tooling in the last year). I was just responding to Paul's lament that there aren't enough "folks pitching in". I know that consistent contributors are really rare – most people just land one or two drive-by patches to fix their itch – which is all the more reason to treat every contributor as a potential high-output contributor.

In my specific case, I was certainly planning to consistently work on Fathom. Talk is cheap, but I think I can substantiate it a bit on account of having developed [my own open source analytics app](https://github.com/zgoat/goatcounter), which is basically now a competitor of Fathom I suppose.

There is also the issue of communication: I had no idea that a "Fathom 2" was in development, and knew even less about your plans to "bring in some paid Go resource". For all outward appearances, the project seemed simply dead. I had assumed you were working on something else. Even a simple "we've paused development on the open source version until the end of the year due to lack of resources", would've made a difference. My response to that would've probably been something along the lines of "Okay, no problem, but maybe we can work together on this thing?"

Like I said in my previous message, I don't want to accuse people of anything, but  IMH(umble)O this could've been handled a bit better.

**Comment by JackEllis** [comment]
@arp242 That’s awesome that you started your own! Best of luck with it! Excited to have an entry level competitor making us work harder ;)

**Comment by dantuluri** [comment]
Another problem I see with keeping v2 closed is the fact that once repos like https://github.com/StevenBlack/hosts get a handle of fathom's domain (simpleanalytics seems to be already on there) it won't be as useful as before where we could host fathom on something.ourdomain.tld. 

I haven't contributed, but for the sake of open-source it'd be great if you could possibly do something like Commento: https://docs.commento.io/contributing/#free-commentoio-access where they give developers free access to their paid tier.

It'd be better if you kept v2 open sourced for all, but at least take some consideration of commento's pricing model for people to use fathom.

**Comment by JackEllis** [comment]
@dantuluri We are currently considering operating 2 codebases, as we don’t want to nuke the current Go codebase and would rather hire help to incrementally improve it. Then we’d focus our energy on the Laravel codebase. No decision has been made yet but your comment is helpful in aiding us with the decision.

**Comment by JackEllis** [comment]
January update since people are confused: We are going to be releasing a new version this year.

**Comment by kaushalyap** [comment]
@JackEllis @pjrvs Is pro version code base proprietary? or is it only new version (v2)?

**Comment by JackEllis** [comment]
@kaushalyap V2 is not open source. We have received a lot of stick from people over this, and we’ve released a podcast episode about it / answered publicly. Because of our movements, we accelerated things significantly. I was responsible for us going closed source, because we tied ourselves to specific infrastructure to reduce DevOps. Because of the moves we’ve made, we are now in a position to work full time on Fathom. We will he working on a new release to Lite later in the year, but the point is that we can dedicate ourselves fully to making this the best product on the market.
